### ISSUE TITLE
[Feat] 메뉴 구조, 페이지 리스트, DB 설계, UI 설계

### ISSUE THREAD

**Issue by jwon42** [humansof42seoul/Humansof42-v2#9]
- [x] 메뉴 구조 (#4 참고)
  <img width="1259" alt="스크린샷 2021-10-07 오후 6 07 34" src="https://user-images.githubusercontent.com/61400214/136355090-f798c2b8-fffe-4297-a22b-f4acba25f4b7.png">

- [x] 페이지 리스트 (#4 참고)
  <img width="1289" alt="스크린샷 2021-10-07 오후 6 08 14" src="https://user-images.githubusercontent.com/61400214/136355120-6508a6f6-227b-46ca-9aa4-7794a879df40.png">
  마이페이지 등의 상세 페이지가 누락되었네요. 업데이트하겠습니다. (2021-10-08)

- [ ] DB 설계 - 관계형db에 대해서 공부가 좀 필요하네요. 수정중입니다.
  https://dbdiagram.io/d/615d59fd825b5b0146236bcc
  - 회원 테이블
    - 42auth 인증 가입 후 이메일 입력을 받아야 함 - 비밀번호 찾기 용도, 가입 시 이메일 인증 필요
   - 관계 되는 요소들간의 연결에 어떤 방법(foreign key, unique key)이 적당한지 작성자, 좋아요수 등 
   - 데이터베이스의 세계도 엄청 넓구나 라는걸 느낌..

- [x] UI 설계 -> #10 이슈로 토스
  - flow chart 및 ui 설계(디자인x) 필요

**Comment by jongfeel** [comment]
조금 쉽게 가기 위해서 table을 따로 쓰는 게 좋을 것 같습니다.
나중에 합치는게 좋을 것 같다는 증거가 확실히 드러나면 그때 해봐도 좋을 것 같네요.

두번째 속도 문제는 게시판 글이 엄청나게 많을 때나 신경 쓸 법한 문제입니다.
그리고 로딩 속도에 문제를 줄 정도라면 적절한 게시글을 갯수만큼 가져와서 처리하는 방법이 있습니다.
